set_property PACKAGE_PIN V10 [get_ports clk]
set_property IOSTANDARD LVCMOS33 [get_ports clk]
set_property IOSTANDARD LVCMOS33 [get_ports x]
set_property PACKAGE_PIN C17 [get_ports x]

set_property PACKAGE_PIN E3 [get_ports clk_in1]
set_property IOSTANDARD LVCMOS33 [get_ports clk_in1]

create_interface interface_1

set_property PACKAGE_PIN E3 [get_ports clk_100]
set_property PACKAGE_PIN C17 [get_ports clk_IP]
set_property PACKAGE_PIN D18 [get_ports clk_my]
set_property IOSTANDARD LVCMOS33 [get_ports clk_IP]
set_property IOSTANDARD LVCMOS33 [get_ports clk_100]
set_property IOSTANDARD LVCMOS33 [get_ports clk_my]

set_property PACKAGE_PIN E3 [get_ports CLK]
set_property IOSTANDARD LVCMOS33 [get_ports CLK]
set_property PACKAGE_PIN T10 [get_ports DS_A]
set_property PACKAGE_PIN R10 [get_ports DS_B]
set_property PACKAGE_PIN K16 [get_ports DS_C]
set_property PACKAGE_PIN K13 [get_ports DS_D]
set_property PACKAGE_PIN P15 [get_ports DS_E]
set_property PACKAGE_PIN J17 [get_ports DS_EN1]
set_property PACKAGE_PIN J18 [get_ports DS_EN2]
set_property PACKAGE_PIN T9 [get_ports DS_EN3]
set_property PACKAGE_PIN J14 [get_ports DS_EN4]
set_property PACKAGE_PIN T11 [get_ports DS_F]
set_property PACKAGE_PIN L18 [get_ports DS_G]
set_property IOSTANDARD LVCMOS33 [get_ports DS_A]
set_property IOSTANDARD LVCMOS33 [get_ports DS_EN1]
set_property IOSTANDARD LVCMOS33 [get_ports DS_C]
set_property IOSTANDARD LVCMOS33 [get_ports DS_B]
set_property IOSTANDARD LVCMOS33 [get_ports DS_D]
set_property IOSTANDARD LVCMOS33 [get_ports DS_E]
set_property IOSTANDARD LVCMOS33 [get_ports DS_EN2]
set_property IOSTANDARD LVCMOS33 [get_ports DS_EN3]
set_property IOSTANDARD LVCMOS33 [get_ports DS_EN4]
set_property IOSTANDARD LVCMOS33 [get_ports DS_F]
set_property IOSTANDARD LVCMOS33 [get_ports DS_G]

set_property PACKAGE_PIN P14 [get_ports DS_EN5]
set_property PACKAGE_PIN T14 [get_ports DS_EN6]
set_property PACKAGE_PIN K2 [get_ports DS_EN7]
set_property PACKAGE_PIN U13 [get_ports DS_EN8]
set_property IOSTANDARD LVCMOS33 [get_ports DS_EN8]
set_property IOSTANDARD LVCMOS33 [get_ports DS_EN7]
set_property IOSTANDARD LVCMOS33 [get_ports DS_EN6]
set_property IOSTANDARD LVCMOS33 [get_ports DS_EN5]
